name: slowtok_camera
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.3
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.2.0
  google_sign_in: ^5.4.4
  dio: ^5.0.0
  shared_preferences: ^2.0.17
  image: ^4.0.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
